version: '3.8'

services:
  # Jaeger - Distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: slip-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    ports:
      - "5775:5775/udp"    # accept zipkin.thrift over compact thrift protocol
      - "6831:6831/udp"    # accept jaeger.thrift over compact thrift protocol
      - "6832:6832/udp"    # accept jaeger.thrift over binary thrift protocol
      - "5778:5778"        # serve configs
      - "16686:16686"      # serve frontend
      - "14250:14250"      # accept model.proto
      - "14268:14268"      # accept jaeger.thrift directly from clients
      - "14269:14269"      # admin port: health check, metrics
      - "4317:4317"        # OTLP gRPC receiver
      - "4318:4318"        # OTLP HTTP receiver
    volumes:
      - jaeger_data:/badger
    networks:
      - tracing
      - slip-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:14269/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  jaeger_data:

networks:
  tracing:
    driver: bridge
  slip-network:
    external: true
