groups:
  - name: api_alerts
    interval: 30s
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: rate(errors_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }}% over 5 minutes"
      
      # Slow response time
      - alert: SlowResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow API response time"
          description: "95th percentile response time is {{ $value }}s"
      
      # High memory usage
      - alert: HighMemoryUsage
        expr: (process_resident_memory_bytes / 1024 / 1024) > 1024
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}MB"
      
      # Database connection pool exhausted
      - alert: DatabasePoolExhausted
        expr: database_connections_active >= database_connections_max * 0.9
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Database connection pool nearly exhausted"
          description: "Database connections at {{ $value }} of maximum"

  - name: slip_verification_alerts
    interval: 30s
    rules:
      # High slip verification failure rate
      - alert: HighSlipVerificationFailureRate
        expr: rate(slip_verifications_total{status="Failed"}[5m]) / rate(slip_verifications_total[5m]) > 0.2
        for: 5m
        labels:
          severity: warning
          component: business
        annotations:
          summary: "High slip verification failure rate"
          description: "More than 20% of slip verifications are failing"
      
      # Slow slip processing
      - alert: SlowSlipProcessing
        expr: histogram_quantile(0.95, rate(slip_processing_duration_seconds_bucket[5m])) > 5
        for: 5m
        labels:
          severity: warning
          component: business
        annotations:
          summary: "Slow slip processing detected"
          description: "95th percentile slip processing time is {{ $value }}s"
      
      # No slip verifications in last 10 minutes (during business hours)
      - alert: NoSlipVerificationsReceived
        expr: rate(slip_verifications_total[10m]) == 0
        for: 10m
        labels:
          severity: info
          component: business
        annotations:
          summary: "No slip verifications received"
          description: "No slip verifications have been processed in the last 10 minutes"

  - name: infrastructure_alerts
    interval: 30s
    rules:
      # High CPU usage
      - alert: HighCPUUsage
        expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 5m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "High CPU usage detected"
          description: "Instance {{ $labels.instance }} has CPU usage above 80% (current: {{ $value }}%)"

      # High Memory usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "High memory usage detected"
          description: "Instance {{ $labels.instance }} has memory usage above 85% (current: {{ $value }}%)"

      # Application down
      - alert: ServiceDown
        expr: up{job=~"api|ocr-service"} == 0
        for: 2m
        labels:
          severity: critical
          component: application
        annotations:
          summary: "Service is down"
          description: "{{ $labels.job }} on {{ $labels.instance }} is down"

      # Database connection issues
      - alert: DatabaseConnectionFailed
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
          component: database
        annotations:
          summary: "Database connection failed"
          description: "PostgreSQL is unreachable"

      # Redis down
      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
          component: cache
        annotations:
          summary: "Redis is down"
          description: "Redis instance is unreachable"

      # Disk space low
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 15
        for: 5m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "Disk space is low"
          description: "Disk space on {{ $labels.instance }} is below 15% (current: {{ $value }}%)"
